version: '3.8'
services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: anurag2911/backend
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - chotaurl-net
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: novell@123
      POSTGRES_DB: shorturl
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - chotaurl-net

  frontend:
    build:
      context: ./client  
      dockerfile: Dockerfile
    image: anurag2911/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - chotaurl-net
    environment:
    - REACT_APP_BACKEND_HOST=backend

networks:
  chotaurl-net:
volumes:
  db-data:
 