version: '3'
services:
  urlshortener:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: anurag2911/backend
    ports:
      - 8080:8080

  web:
    build:
      context: ./client  
      dockerfile: Dockerfile
    image: anurag2911/frontend
    ports:
      - 3000:3000
    depends_on:
      - urlshortener