version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: anurag2911/backend
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: novell@123
      POSTGRES_DB: shorturl
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: anurag2911/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

    environment:
      - REACT_APP_BACKEND_HOST=backend

volumes:
  db-data:
