version: '3'
services:
  urlshortener:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: anurag2911/backend
    ports:
      - 8080:8080
    links:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: novell@123
      POSTGRES_DB: shorturl
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: ./client  
      dockerfile: Dockerfile
    image: anurag2911/frontend
    ports:
      - 3000:3000
    depends_on:
      - urlshortener